name:                fp-lab3
version:             0.1.0.0
github:              "WWamich/fp-lab3"
license:             BSD-3-Clause
author:              "WWamich" 
maintainer:          "admiral3233@mail.ru"

ghc-options:
- -Wall
- -Werror
- -Wno-type-defaults 

dependencies:
- base >= 4.7 && < 5
- vector
- hashable

library:
  source-dirs: src
  exposed-modules:
  - Interpolation
  - Data.Interpolation.Internal

tests:
  fp-lab3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
    dependencies:
    - fp-lab3
    - tasty
    - tasty-hunit
    - tasty-quickcheck 
    - QuickCheck       

